export const NS_PER_NANOSECOND = 1;
export const NS_PER_MICROSECOND = 1000 * NS_PER_NANOSECOND;
export const NS_PER_MILLISECOND = 1000 * NS_PER_MICROSECOND;
export const NS_PER_SECOND = 1000 * NS_PER_MILLISECOND;
export const NS_PER_MINUTE = 60 * NS_PER_SECOND;
export const NS_PER_HOUR = 60 * NS_PER_MINUTE;
